### ISSUE TITLE
How to not show environment color?

### ISSUE THREAD

**Issue by engineer1109** [terier/vpt#1]
When set environment white, the background will also turn white.
How to not show environment color on background?

**Comment by CirilBohak** [comment]
There is no support for this in the main branch yet. There is support in the "multi-channel-volumes" branch, where you can override the background color and also rotate the environmental map.

**Comment by engineer1109** [comment]
@CirilBohak 
Thanks for answers.
And for background clear color, "if (photon.bounces < 1u)" will be better.

**Comment by CirilBohak** [comment]
It depend on the use-case :) This is why we did not yet include it into the main branch :)
